generate_general: false
generate_specific: false
specific:
  add: {"6A": "?", "HO": "?", "SI": "?"}
  remove: ["-"]

combine_systems:
  enable: true
  systems_config: 
    "/root/dev/VPAlgo-LimitH2-V1/results/V1.0/V5.0 mit Zeitfilter Sharpe als Berechnung": 
      risk: "0.5"
      add:
        "HO": "?"
    "/root/dev/VPAlgo-LimitH2-V2/results/V5.0 Entry als Ankerpunkt zur TP-Berechnung/V3.0 Mit ZeitFilter, Mit Sharpe": 
      risk: "1"
      add:
        "HO": "14"
      remove:
        - "NG"