generate_general: false
generate_specific: true
specific:
  add: {"6A": "?", "HO": "14", "SI": "?"}
  remove: ["NG"]

combine_systems:
  enable: false
  other_systems_dirs: 
    - "/root/dev/VPAlgo-LimitH2-V1/results/V1.0/V5.0 mit Zeitfilter Sharpe als Berechnung"